fix(pingcap/monitoring): fix updating job (#2818)
When failed, we should not commit and push the changes(the tool will
delete the dir firstly).

Signed-off-by: wuhuizuo <wuhuizuo@126.com>

diff --git a/prow-jobs/pingcap-monitoring-periodics.yaml b/prow-jobs/pingcap-monitoring-periodics.yaml
--- a/prow-jobs/pingcap-monitoring-periodics.yaml
+++ b/prow-jobs/pingcap-monitoring-periodics.yaml
@@ -28,12 +28,16 @@ periodics:
           command: [bash, -ceo, pipefail]
           args: &args
             - |
-              go run ./cmd/monitoring.go --tag $TARGET --config monitoring.yaml --token $(cat /etc/github/token)
-              git add monitor-snapshot/$TARGET
-              # should ignore the file: monitor-snapshot/$TARGET/ansible-monitor.tar.gz, it will be different in every compressing.
-              if git diff --cached --exit-code --name-status monitor-snapshot/$TARGET/operator; then
-                echo "🤷 No changes happened."
-                exit 0
+              if go run ./cmd/monitoring.go --tag $TARGET --config monitoring.yaml --token $(cat /etc/github/token); then
+                git add monitor-snapshot/$TARGET
+                # should ignore the file: monitor-snapshot/$TARGET/ansible-monitor.tar.gz, it will be different in every compressing.
+                if git diff --cached --exit-code --name-status monitor-snapshot/$TARGET/operator; then
+                  echo "🤷 No changes happened."
+                  exit 0
+                fi
+              else
+                echo "❌ tool run failed!"
+                exit 1
               fi
 
               # commit and push the changes
